
flappybird1:
  env_id: FlappyBird-v0
  replay_memory_size: 50000
  mini_batch_size: 32
  epsilon_init: 0.1
  epsilon_decay: 0.99995
  epsilon_min: 0.00001
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  input_channels: 3

flappybird:
  env_id: FlappyBird-v0
  replay_memory_size: 100
  mini_batch_size: 32
  epsilon_init: 1
  epsilon_decay: 0.99995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  input_channels: 3
#default:
#  env_id: "FlappyBird-v0"
#  replay_memory_size: 10000
#  mini_batch_size: 32
#  epsilon_init: 1.0
#  epsilon_decay: 0.995
#  epsilon_min: 0.1
#  learning_rate_a: 0.0001
#  discount_factor_g: 0.99
#  network_sync_rate: 1000
#  stop_on_reward: 200

